apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  namespace: monitoring
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-monitoring
  nfs:
    server: 192.168.25.139
    path: "/Monitoring/loki-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-monitoring
  resources:
    requests:
      storage: 30Gi