server:
  persistentVolume:
    enabled: true
    existingClaim: prometheus-pvc
    size: 20Gi
  
  retention: "30d"
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  service:
    type: ClusterIP
    port: 9090

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - prometheus.your-domain.com

alertmanager:
  enabled: true
  persistentVolume:
    enabled: false

pushgateway:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true